#!/usr/bin/env python 3                                                                                                                                                                                                                      # Shebang
import random

print("The False Chrysanthemum's Sunflower")                                                                                                                                                                                                 # Game Title
name = input("Konnichiwa. I am Watannabe Tomo, the Second Administrator to the office of the Ambassator. You must be the US military detective we've been waiting for. I am afraid I wasn't provided your name. What is your name, sir? ")   # Greeting and Name Request
first = input(f"Yes, Lieutenant {name}. We can start with explaining what seems to have happened, if you'd like? ")                                                                                                                          # Response to begin
print("Unfortunately, we don't know much yet. All we have is a body found in the garden of this estate. It's a high-ranking government official, and there are signs of foul play.")                                                         # Exposition
second = input("Would you like to see the crime scene? ")                                                                                                                                                                                    # Request to proceed
print("Yes, sir. We've cordoned off the entire estate. Only authorized personnel are allowed in. Please follow me, sir.")                                                                                                                    # Description of the scene
print("We found the body just over there. It appears that the victim was struck on the head with a blunt object. He's wearing a US officer's uniform")                                                                                       # Description of victim
third = input("Is there anything else, sir? ")                                                                                                                                                                                               # Interaction that leads to progression
print("Yes, sir. You'll want to interview everyone immediately after seeing the crime scene to discover any possible motives. Everyone has been held for the time, so there is no reason to rush.")                                          # Reminder to speak to the suspects
searching = input("Is there anywhere you'd like to begin searching? ")                                                                                                                                                                       # Request of where to search first
print(f"Of course. We can begin with {searching}. I will assist you in any way we can.")                                                                                                                                                     # Player picks something to search and find a clue
clue = random.choice(["matchbook", "coin", "business card"])                                                                                                                                                                                 # Random Clue assigned
print(f"Sir, did you notice the {clue} next to the body? Did you want to look at it? ")                                                                                                                                                      # Clue mentioned as reward for searching
if clue == "matchbook":                                                                                                                                                                                                                      # if matchbook was selected
    print(f"The {clue} is for a hotel in the Rippongi district, which is full of bars favored by foreigners and gangsters.")                                                                                                                 # Matchbook clue exposition
elif clue != "matchbook":                                                                                                                                                                                                                    # matchbook wasn't selected
    if clue == "coin":                                                                                                                                                                                                                       # if coin was selected
        print(f"The {clue} is not a Japanese {clue}. That's a Korean 500 won coin! ")                                                                                                                                                        # coin exposition
    else:                                                                                                                                                                                                                                    # if business card was selected
        print(f"That {clue} is for a Mr. Yoshi, an importer with Yasuda. Yasuda is a mega corporation here in Japan that we call a Zaibatsu.")                                                                                               # business card exposition
print(f"What's that commotion with the suspects? We can return to searching the {searching} in a moment. It sounds like the suspects are getting restless. Sense you mentioned wanting to interview them, shall we? ")                       # commotion with suspects
interview = input(f"Inspector {name}, who did you want to interview first? There are three suspects. The guard that weas on duty, a clerk that was working late, and a night deliveryman? ")                                                 # first suspect to be interviewed
if interview == "clerk":                                                                                                                                                                                                                     # if clerk was selected
    print(f"The {interview} says he was working late to transcribe his meeting notes when he heard there was an alarm. He says he thinks it was the deliveryman and wants him arrested so that he can finish up and go home for the night.") # Clerk exposition
elif interviw != "clerk":                                                                                                                                                                                                                    # Clerk wasn't selected
    if interview == "deliveryman":                                                                                                                                                                                                           # if deliveryman was selected
        print(f"The {interview} seems confused as he has to notify his bos soon about this delay and ays he doesn't know why they are being held when he has deliveries to make.")                                                           # deliveryman exposition
    else:                                                                                                                                                                                                                                    # if guard was selected
        print(f"That {interview} guard said he found the body soon after letting the clerk and delivery man in. He said he imediately sounded the alarm and he didn't know anyone else was in the building.")                                # guard exposition